### ISSUE TITLE
Custom cat css border-image, cursor, and react.js cat shimeji.

### ISSUE THREAD

**Issue by AltheimIcarus** [AltheimIcarus/Qwiki#12]
Design a cute cat border for div container, a cat cursor and a react.js pet cat shimeji.

**Comment by dynaput247** [comment]
Hello
May I work on opened issues?
If you need my help, contact with me:
telegram: https://t.me/dynaput247
discord: MVP (84478447)
gmail: toptalent48@gmail.com
skype: live:.cid.b5e7c8f996fa441a

**Comment by AltheimIcarus** [comment]
> Hello May I work on opened issues? If you need my help, contact with me: telegram: https://t.me/dynaput247 discord: MVP (84478447) gmail: [toptalent48@gmail.com](mailto:toptalent48@gmail.com) skype: live:.cid.b5e7c8f996fa441a

Sure, it's a fun side project so I hope if anyone would be amused to use or work on it too.

**Comment by AltheimIcarus** [comment]
@dynaput247 Maybe you will be interested to check on my progress on the react.js Shimeji repo here:

[https://github.com/AltheimIcarus/Shimeji-React](https://github.com/AltheimIcarus/Shimeji-React)

**Comment by AltheimIcarus** [comment]
Completed Shimeji in js and React.js project in [https://github.com/AltheimIcarus/Shimeji-React](https://github.com/AltheimIcarus/Shimeji-React) and in commit 44f43f5eb858523684d6da9fc0339af22b394d17 of [markdownEditor](../tree/markdownEditor) branch. Will merge with main branch hence closing this issue.
